services:
  # Rust Backend
  spp-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - SOLANA_RPC_URL=https://api.devnet.solana.com
      - SOLANA_RPC_URL_ALT=https://devnet.solana.rpcpool.com
      - BUNDLR_URL=https://node1.bundlr.network
      - KEYPAIR_PATH=/app/keypair.json
    volumes:
      - ./backend/keypair.json:/app/keypair.json:ro
    networks:
      - spp-network
    restart: unless-stopped

  # Frontend (React)
  spp-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
      - REACT_APP_SOLANA_NETWORK=devnet
    depends_on:
      - spp-backend
    networks:
      - spp-network
    restart: unless-stopped

volumes:
  redis-data:
  postgres-data:

networks:
  spp-network:
    driver: bridge 